// <auto-generated />
using System;
using AcessoDados.DAL.EntityCodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcessoDados.DAL.Migrations
{
    [DbContext(typeof(CodeFirstDBContext))]
    [Migration("20190528181408_CorrigirColuna")]
    partial class CorrigirColuna
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCriacao");

                    b.Property<bool>("FlagExcluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.Responsavel", b =>
                {
                    b.Property<int>("IdResponsavel")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCriacao");

                    b.Property<bool>("FlagExcluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("IdResponsavel");

                    b.ToTable("Responsavel");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.Video", b =>
                {
                    b.Property<int>("IdVideo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCriacao");

                    b.Property<bool>("FlagExcluido");

                    b.Property<int>("IdResponsavel");

                    b.Property<int?>("IdadeMinima");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("IdVideo");

                    b.HasIndex("IdResponsavel");

                    b.HasIndex("IdadeMinima")
                        .HasName("IX_VIDEO_IDADE");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.VideoCategoria", b =>
                {
                    b.Property<int>("IdVideoCategoria")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCriacao");

                    b.Property<bool>("FlagExcluido");

                    b.Property<int>("IdCategoria");

                    b.Property<int>("IdVideo");

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("IdVideoCategoria");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdVideo");

                    b.ToTable("VideoCategoria");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.Video", b =>
                {
                    b.HasOne("AcessoDados.DAL.EntityCodeFirst.Modelos.Responsavel", "Responsavel")
                        .WithMany("Videos")
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.VideoCategoria", b =>
                {
                    b.HasOne("AcessoDados.DAL.EntityCodeFirst.Modelos.Categoria", "Categoria")
                        .WithMany("VideoCategorias")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AcessoDados.DAL.EntityCodeFirst.Modelos.Video", "Video")
                        .WithMany("VideoCategorias")
                        .HasForeignKey("IdVideo")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
